import type { Inspiration } from '@/types';

/** Fictional reference — written by the Atmos editorial desk. */
export const observatory: Inspiration = {
  id: 'observatory',
  title: 'Observatory',
  category: 'Experimental',
  tags: ['data art', 'particle sky', 'generative', 'night-sky palette'],
  summary: 'A data-art experience that renders a fictional year of night-sky observations as a breathing particle sky.',
  analysis:
    'Data is the aesthetic: thousands of observations become stars whose brightness, color temperature, and drift encode real values, while a narration line types itself underneath. It is data visualization with the restraint of an planetarium show — axes and legends exist, but they whisper from the edges.',
  dna: {
    typography:
      'A luminous mono for readouts and coordinates; a spare grotesk for chapter titles; annotations set at 11px like telescope logbook entries.',
    color:
      'Night blues on #07080c with starlight whites and one warm amber for solar values; luminance encodes the data, chroma stays restrained.',
    layout:
      'One full-bleed canvas sky; chapter titles and a typed narration line anchor the lower third; a minimal legend and axis ticks frame the edges.',
    motion:
      'Stars twinkle on independent 4–9s cycles; constellations connect with 600ms line draws; the sky slowly rotates 30° per chapter via camera drift.',
    interaction:
      'Scrubbing a timeline replays the year; hovering a star cluster reveals its story in the margin; a "labels" overlay switches between art mode and annotated mode.',
  },
  buildPrompt: `Design an original data-art experience for {{brand}} — {{industry}} presenting {{product}} — rendered as a breathing night sky.

CONCEPT
A fictional year of night-sky observations becomes the interface: thousands of stars whose brightness, color temperature, and drift encode real values from a generated dataset. The page behaves like a planetarium show with the restraint of a gallery piece.

LAYOUT & HIERARCHY
- One full-bleed sky owns the canvas; narration types itself, line by line, in the lower third.
- Chapters divide the year (Winter, Spring, Summer, Autumn); a minimal legend and axis ticks whisper from the edges — legible, never loud.
- An "annotated mode" toggle overlays exact values, cluster names, and gridlines for visitors who want the science with the art.

VISUAL MOOD
High-altitude darkness at 3 a.m.: deep night blues, starlight whites, a single warm amber for solar values. Luminance carries the data; chroma stays disciplined.

TYPOGRAPHY
A luminous mono for coordinates, dates, and readouts; a spare grotesk for chapter titles; 11px annotations styled as telescope logbook entries with dates and initials.

COLOR
Night ground #07080c, starlight whites at varying luminance, cool blue-greens for density fields, {{accent}} amber exclusively for solar and event markers.

MOTION & INTERACTION
Stars twinkle on independent 4–9s cycles (never synchronized); constellation lines draw in over 600ms; the sky drifts 30° per chapter. A timeline scrubs the whole year (arrow keys step months); hovering a cluster surfaces its story in the margin. Reduced motion: static sky, instant narration, timeline still functional.

RESPONSIVE BEHAVIOR
Star count scales with viewport (≈ 1 star per 1,500px², capped for mobile GPUs); the timeline docks to the bottom edge; annotated mode stacks legends above the sky rather than beside it.

ACCESSIBILITY
The full dataset narrative exists as an article below the canvas — the sky is enhancement, with aria-hidden and a text alternative summary. All readouts and annotations pass 4.5:1. Scrubbing is possible entirely by keyboard.

TECHNICAL DIRECTION
React + TypeScript + Tailwind; a single <canvas> with a typed render loop (no physics engine) or layered CSS particles for the static mode; dataset generated by a seeded PRNG so the artwork is reproducible; Framer Motion for panel transitions only.

ORIGINALITY
Generate your own dataset with a seeded algorithm, write the narration, and design your own encodings. Do not reproduce real catalog data, existing data-art pieces, or anyone's code.`,
  customization: {
    brand: 'Observatory',
    industry: 'a data-art practice',
    product: 'a year of night-sky observations',
    tone: 'hushed and curious',
    accent: '#ffc266',
  },
  source: {
    label: 'observatory.example',
    url: 'https://example.com/inspirations/observatory',
    credit: 'Fictional credit — The Night Desk',
  },
  createdAt: '2026-08-30',
  baseSaves: 131,
  thumb: { variant: 'field', palette: ['#07080c', '#141a26', '#ffc266'], ratio: 'tall' },
  origin: 'seed',
};
